from abc import ABC, abstractmethod

class Player(ABC):

    @abstractmethod
    def play(self, url: str) -> None: ...

    @abstractmethod
    def pause(self) -> None: ...

    @abstractmethod
    def resume(self) -> None: ...

    @abstractmethod
    def stop(self) -> None: ...

    @abstractmethod
    def set_volume(self, volume: int) -> int: ...

    @abstractmethod
    def get_volume(self) -> int: ...

    @abstractmethod
    def set_end_callback(self, callback) -> None: ...

    @abstractmethod
    def get_state(self) -> str: ...

    @abstractmethod
    def get_time_pos(self) -> float | None: ...

    @abstractmethod
    def seek(self, seconds: int) -> None: ...

    @abstractmethod
    def is_paused(self) -> bool: ...

    @abstractmethod
    def is_idle(self) -> bool: ...
